In [2]:
from tensorflow.contrib.learn.python.learn.datasets import base


In [1]:

# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import tensorflow as tf
import numpy as np
print(tf.__version__)

from tensorflow.contrib.learn.python.learn.datasets import base

# Data files
IRIS_TRAINING = "iris_training.csv"
IRIS_TEST = "iris_test.csv"

# Load datasets.
training_set = base.load_csv_with_header(filename=IRIS_TRAINING,
                                         features_dtype=np.float32,
                                         target_dtype=np.int)
test_set = base.load_csv_with_header(filename=IRIS_TEST,
                                     features_dtype=np.float32,
                                     target_dtype=np.int)

# Specify that all features have real-value data
feature_name = "flower_features"
feature_columns = [tf.feature_column.numeric_column(feature_name, 
                                                    shape=[4])]
classifier = tf.estimator.LinearClassifier(
    feature_columns=feature_columns,
    n_classes=3,
    model_dir="/tmp/iris_model")

def input_fn(dataset):
    def _fn():
        features = {feature_name: tf.constant(dataset.data)}
        label = tf.constant(dataset.target)
        return features, label
    return _fn

# Fit model.
classifier.train(input_fn=input_fn(training_set),
               steps=1000)
print('fit done')

# Evaluate accuracy.
accuracy_score = classifier.evaluate(input_fn=input_fn(test_set), 
                                     steps=100)["accuracy"]
print('\nAccuracy: {0:f}'.format(accuracy_score))

# Export the model for serving
feature_spec = {'flower_features': tf.FixedLenFeature(shape=[4], dtype=np.float32)}

serving_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)

classifier.export_savedmodel(export_dir_base='/tmp/iris_model' + '/export', 
                            serving_input_receiver_fn=serving_fn)

1.3.0
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/iris_model', '_tf_random_seed': 1, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/iris_model/model.ckpt.
INFO:tensorflow:loss = 131.833, step = 1
INFO:tensorflow:global_step/sec: 1088.28
INFO:tensorflow:loss = 37.1391, step = 101 (0.093 sec)
INFO:tensorflow:global_step/sec: 1312.47
INFO:tensorflow:loss = 27.8594, step = 201 (0.076 sec)
INFO:tensorflow:global_step/sec: 1264.61
INFO:tensorflow:loss = 23.0449, step = 301 (0.079 sec)
INFO:tensorflow:global_step/sec: 1284.84
INFO:tensorflow:loss = 20.058, step = 401 (0.078 sec)
INFO:tensorflow:global_step/sec: 786.881
INFO:tensorflow:loss = 18.0083, step = 501 (0.127 sec)
INFO:tensorflow:g

b'/tmp/iris_model/export/1508481316'

In [2]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

1.3.0


In [3]:
from tensorflow.contrib.learn.python.learn.datasets import base

# Data files
IRIS_TRAINING = "iris_training.csv"
IRIS_TEST = "iris_test.csv"

# Load datasets.
training_set = base.load_csv_with_header(filename=IRIS_TRAINING,
                                         features_dtype=np.float32,
                                         target_dtype=np.int)
test_set = base.load_csv_with_header(filename=IRIS_TEST,
                                     features_dtype=np.float32,
                                     target_dtype=np.int)

print(training_set.data)

print(training_set.target)

[[ 6.4000001   2.79999995  5.5999999   2.20000005]
 [ 5.          2.29999995  3.29999995  1.        ]
 [ 4.9000001   2.5         4.5         1.70000005]
 [ 4.9000001   3.0999999   1.5         0.1       ]
 [ 5.69999981  3.79999995  1.70000005  0.30000001]
 [ 4.4000001   3.20000005  1.29999995  0.2       ]
 [ 5.4000001   3.4000001   1.5         0.40000001]
 [ 6.9000001   3.0999999   5.0999999   2.29999995]
 [ 6.69999981  3.0999999   4.4000001   1.39999998]
 [ 5.0999999   3.70000005  1.5         0.40000001]
 [ 5.19999981  2.70000005  3.9000001   1.39999998]
 [ 6.9000001   3.0999999   4.9000001   1.5       ]
 [ 5.80000019  4.          1.20000005  0.2       ]
 [ 5.4000001   3.9000001   1.70000005  0.40000001]
 [ 7.69999981  3.79999995  6.69999981  2.20000005]
 [ 6.30000019  3.29999995  4.69999981  1.60000002]
 [ 6.80000019  3.20000005  5.9000001   2.29999995]
 [ 7.5999999   3.          6.5999999   2.0999999 ]
 [ 6.4000001   3.20000005  5.30000019  2.29999995]
 [ 5.69999981  4.4000001   1.5 